### ISSUE TITLE
Build command option not used

### ISSUE THREAD

**Issue by projectjudge** [ojkelly/yarn.build#11]
When running the following command `yarn build -c test`, yarn.build still runs the `build` command script rather than `test` as expected.

The issue appears to be in this [line](https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/build/index.ts#L109) where it is not using the input command [argument](https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/build/index.ts#L84)

## Proposed solution

Use the command argument as follows:

```typescript
(await this.cli.run(["run", command || "build"], {
```

Happy to submit a PR for this :)

**Comment by ojkelly** [comment]
Yep this would be great to fix. A PR would be very welcome. I think you’re suggestion will work.

Long term I’d like to map `yarn test` (#7) the same way `yarn build` is setup. But I also want to add config, so you can remap them if want something else, because they’re very common commands (#3).

**Comment by projectjudge** [comment]
Great to hear that you've got plans for `yarn test` as well! I'll get a PR out with my suggestion

**Comment by oliversalzburg** [comment]
Because `command` is `this.buildCommand` from the command instance, the default value is already `"build"`. I submitted a PR with the relevant change.
