### ISSUE TITLE
Failing to run on windows

### ISSUE THREAD

**Issue by ojkelly** [ojkelly/yarn.build#12]
Reports of yarn build` not working on Windows.

If you have this issue please comment below with some more information. 

If you know the fix already a PR is welcome.

**Comment by oliversalzburg** [comment]
The `cwd` property in the `project` will be, for example, `/C:/oliver/my-project`. That will be interpreted by Windows as _at the root of the current drive, look in the folder named `C:`_. Which is not what you'd want 😄

This will then be translated to `C:\C:\oliver\my-project` by Windows, which doesn't exist.

**Comment by oliversalzburg** [comment]
Here's a fix for the path related issues: https://github.com/oliversalzburg/yarn.build/commit/3d8bc6b0b7746a3b3d3f84abe7febc79540143b8

But now it's getting stuck at: `TypeError: process.stdout.cursorTo is not a function` 😞

**Comment by valdestron** [comment]
Just tested using docker.
Same error.

```
FROM node:14.15.1-alpine as bundler
WORKDIR usr/src/app

ADD . .

RUN yarn install
RUN yarn workspace @packages/service build
```

```
/usr/src/app/.yarn/plugins/@ojkelly/plugin-build.cjs:5
TypeError: process.stdout.cursorTo is not a function
    at L.waitUntilDone (/usr/src/app/.yarn/plugins/@ojkelly/plugin-build.cjs:5:13205)
    at Immediate.<anonymous> (/usr/src/app/.yarn/plugins/@ojkelly/plugin-build.cjs:5:13009)
    at processImmediate (internal/timers.js:461:21)
```
yarn 2.4.0
yarn.build latest
