### ISSUE TITLE
[Build] ignore file support or multiple "output" folders

### ISSUE THREAD

**Issue by skoging** [ojkelly/yarn.build#143]
**Is your feature request related to a problem? Please describe.**
I have a monorepo with several create-react-app projects, along with a number of common dependencies built with `tsc`. This tool works great for all of the dependencies, but I'm having issues configuring for use with `create-react-app` projects. These are the main cause of our slow builds, and what I was hoping this tool could help with.

The issue is that create-react-app is configured by default to output build cache to `node_modules/.cache/` in addition to the build artifacts in `build/`.

**Describe the solution you'd like**
Either the ability to specify an array of output folders in package.json:
```json
{
  "yarn.build": {
    "input": ".",
    "output": ["build", "node_modules/.cache"]
  }
}
```

Or support for using the `.gitignore` or another ignore file to ignore files/folders when checking the cache.

I'm not sure if there are any potential issues with ignoring `node_modules` by default or using `.gitignore` by default, but making this work with common tools like `create-react-app` without config would be ideal.

**Comment by ojkelly** [comment]
This should be reasonably easy to add.

Just need to update the config https://github.com/ojkelly/yarn.build/blob/main/packages/plugins/plugin-build/src/config.ts#L13

and then just need to update this function to handle the array
https://github.com/ojkelly/yarn.build/blob/main/packages/plugins/plugin-build/src/supervisor/index.ts#L514

I don't have free time to get to this for a little while, is this something you'd be willing to try and make a PR for?

**Comment by skoging** [comment]
I took a stab at it.

Also reused the config validation for "yarn.build" section of package.json
