### ISSUE TITLE
Support input files in addition to folders

### ISSUE THREAD

**Issue by skoging** [ojkelly/yarn.build#151]
Files are already supported as output, since each file in the input folders are checked against the output with `input.startsWith(output)`.

Multiple inputs and outputs are supported, making files as part of input or output a more likely scenario. This should work as expected.

**Comment by ojkelly** [comment]
Is this for `build` or `bundle`?

Can you give an example command of what you're thinking?

Files as input to me probably wont work for either. As both `build` and `bundle` operate on workspaces as their smallest unit.
