### ISSUE TITLE
Exclude workspaces by name from build

### ISSUE THREAD

**Issue by RDIL** [ojkelly/yarn.build#153]
**Is your feature request related to a problem? Please describe.**

Yeah, docusaurus has some packages that need to be workspaces but should not be built with the rest of the packages, but writing an explicit list of targets would be quite long.

**Describe the solution you'd like**
Something like `yarn build --exclude packages/create-docusaurus/classic,packages/create-docusaurus/classic-typescript,packages/create-docusaurus/facebook`, or, even better, a config file option.

**Describe alternatives you've considered**
I haven't really considered any alternatives.

**Additional context**
https://github.com/facebook/docusaurus/pull/6028

**Comment by ojkelly** [comment]
Yeah this is something I've been thinking about too.

Would this be per package? or just overall?

**Comment by RDIL** [comment]
Overall.  We are just using `yarn build` with no arguments right now, and so having it never attempt to build the template packages would be ideal.

**Comment by ojkelly** [comment]
Yeah cool, that should be pretty quick to add.

I can probably get it done shortly.

I've been looking at something similar to allow opting out of building things like golang workspaces. But still wanting them there, so they can be built in CI.

**Comment by ojkelly** [comment]
@RDIL sorry this one took a while, but it's in there now if you're still interested :)

`--exclude [path|name]` supports globs, and also `--exclude-current` for use in a dev watching command such as `yarn build --exclude-current && docusaurus-start --watch`
