### ISSUE TITLE
Fail early when building dependent projects

### ISSUE THREAD

**Issue by jeffrson** [ojkelly/yarn.build#178]
**Is your feature request related to a problem? Please describe.**

Say, there are 4 projects in a mono-repo: prj1, prj2 (depending on prj1), prj3 (depending on prj1), prj4 (depending on prj2, prj3).
Currently, afaict, from my real world mono-repo, prj1 is built, then prj2 and prj3, then prj4 - even if prj1 fails to build! Even more, it seems, that the cached file information prevents another build (such that "-r" needs to be used).

**Describe the solution you'd like**
yarn.build should fail as soon as possible. If there are some projects built in parallel those should not be stopped of course:
prj1 fails - no other prj will be built
prj2 fails - prj1 had been built before, proj3 will be built, prj4 will not be built

Cache information will only be written for projects that have been built successfully.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by ojkelly** [comment]
Thanks for this report, I had noticed some similar behaviour. I think I've fixed this in the next release, including preventing dependencies from being built of a failed build.

`yarn build --bail` didn't work correctly, has been fixed, and is now the default.

`yarn build --continue-on-error` will allow the previous behaviour.
