### ISSUE TITLE
yarn build -c: concurrency

### ISSUE THREAD

**Issue by leshkovichpvl** [ojkelly/yarn.build#204]
I've noticed that when you run `yarn build -c`, if one of jobs takes a long time to complete, then only that job is processed until it completes.
It works like `max-concurrency = 1`.

Maybe because I'm running `yarn build -c lint` and expecting jobs to run in all workspaces in parallel? 
Is this happening because of the Dependency Graph? Is it possible to make the mode ignore the Dependency Graph, because I can safely run yarn build -c lint in all workspaces?

**Comment by ojkelly** [comment]
yeah it's likely the dependency graph getting you there. It's tightly baked into how yarn.build wants to operate.

Thankfully what you want is in the yarn cli itself, `yarn workspaces foreach -p lint`

https://yarnpkg.com/cli/workspaces/foreach
