### ISSUE TITLE
`yarn bundle` is adding a root folder which breaks compatibility with lambda

### ISSUE THREAD

**Issue by ojkelly** [ojkelly/yarn.build#217]
**Describe the bug**
a root folder called `bundle` is added to the zip.

**Expected behavior**

the repo is added directly with no root folder.

**Additional context**
It looks like this appeared at some point in the codebase.

**Comment by jpwilliams** [comment]
Has this been released yet? Still seeing this! 😲

**Comment by ojkelly** [comment]
Ah sorry not yet, I was testing some other changes. I'll get a new release cut very soon.

**Comment by ojkelly** [comment]
@jpwilliams v3.6.0 is out with this fix.
