### ISSUE TITLE
Figuring out run order is taking too long

### ISSUE THREAD

**Issue by srich-kr** [ojkelly/yarn.build#238]
**Describe the bug**
I think the script is taking too long to figure out the run order.

**To Reproduce**
1. Take a huge monrepo with 300 packages
2. Run build in the root directory
3. Look at the build time at the end of the logs and compare it with the total execution time.

**Expected behavior**
I expect yarn build to be fast. In my case, it took 30 mins in total but yarn.build says that the build time was 6 mins.

**Screenshots**
<img width="1229" alt="Screen Shot 2022-10-12 at 3 57 09 PM" src="https://user-images.githubusercontent.com/61600644/195435910-f81503ab-bead-4133-b513-efad16eb9cb0.png">

**Desktop**
 - OS: Linux

**Comment by ojkelly** [comment]
Thanks for this bug report.

This would suggest it spent 26 minutes determining how to build it?

Do you have any more information on the nature of the packages?

For 300 packages, I would expect it to take under a second or so to work out the build order, so something it definitely odd.

Any chance you can create a repro repo?

I'll try and do some testing too.
