### ISSUE TITLE
Support glob patterns for input/output paths?

### ISSUE THREAD

**Issue by Ambient-Impact** [ojkelly/yarn.build#239]
**Is your feature request related to a problem? Please describe.**

In some projects, we have a lot of smaller components that are grouped into their own directories, where the source SCSS files live in the same place as the compiled CSS files. Technically, it would be possible to move all the compiled CSS into a dist directory of some kind, but it likely be a lot of work and possibly cause unexpected problems. I know the common wisdom is to have a separate dist directory for compiled stuff, but in some projects this feels like it makes less sense.

If we already know ahead of time that SCSS files are the only ones that are going to be built via our `build` script, then `yarn build` could ignore all other files and directories that aren't/don't contain SCSS files.

To put it more visually, here's a subset of a directory tree:

![sublime_text_w3e35K8uMd](https://user-images.githubusercontent.com/2289006/200430303-3a35fda3-308f-4737-b6fb-e0b4517d28cd.jpg)

Currently, any modification to any of those files causes `yarn build` to rebuild it all, but it would be very handy if it could ignore changes to all but the SCSS files.

**Describe the solution you'd like**

Support [glob](https://www.npmjs.com/package/glob) patterns? I'm not sure what the performance implications of this might be, however. I'm on a high end SSD, though, so globbing is fairly fast on my hardware, but may not be as performant on lower end hardware.

**Describe alternatives you've considered**

Long term, I plan to break up a lot of these into smaller packages, but it'll require a lot of work and may still run into this problem.

**Additional context**

Drupal libraries compiled via Webpack? Not sure what else to provide.

**Comment by ojkelly** [comment]
In https://github.com/ojkelly/yarn.build/pull/232 glob support was added to input/output.

Try the following in `package.json` of the package.

```
  "yarn.build": {
    "input": [
      "src/**",
      "!src/**/*.css"
    ],
    "output": [
      "src/**/*.css"
    ]
  },
```

**Comment by Ambient-Impact** [comment]
Well that's awesome to hear. Thanks!
