### ISSUE TITLE
yarn build does not recognize a global workspace command

### ISSUE THREAD

**Issue by ulrik-s** [ojkelly/yarn.build#252]
We are big Yarn2+ fans, thanks for a great plugin!

I have an eslint global script command defined in my workspace root-package.json:
"g:eslint" and I have not found any way to make the plugin exectute it. Maybe there is a trick
or docs I have missed and if so I would be really grateful for a pointer in the right direction.

When I try to execute the global script with yarn build:

```
yarn build -c g:eslint


[ Summary ]---------------------------------------------------------------------
Success: 0
Up to date: 0
Fail: 0
Skipped: 0
Excluded: 0
Total: 0
---
Runtime (wall): 0.01s
[ g:eslint finished ]---------------------------------------------[ yarn.build ]
```

**Describe the solution you'd like**
The behavior should IMHO be the same as 
```
yarn workspace wksp g:eslint
```
or 
```
cd path/to/wksp && yarn g:eslint
```

**Comment by ojkelly** [comment]
Closing this as the desired behaviour is native to yarn, and works well in that context.
