### ISSUE TITLE
Yarn 4 build failing 

### ISSUE THREAD

**Issue by cmark1302** [ojkelly/yarn.build#266]
**Describe the bug**
Yarn 4 build failing 

**To Reproduce**
1. yarn set version berry
2. yarn install
3. Run command 'yarn build'

**Expected behavior**
yarn build should success without any error

**Screenshots**
Type Error: Cannot read properties of undefined (reading 'scope')

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by sjayach** [comment]
Added a PR to support Yarn 4

https://github.com/ojkelly/yarn.build/pull/267

@ojkelly

**Comment by cmark1302** [comment]
Thank you @sjayach
