### ISSUE TITLE
Unreliable Yarn 4 Behavior

### ISSUE THREAD

**Issue by Animalmix55** [ojkelly/yarn.build#268]
**Describe the bug**
When using Yarn 4.0.2, upgraded from Yarn 3, running `yarn plugin import https://yarn.build/latest` and then `yarn bundle` results in the following error

![image](https://github.com/ojkelly/yarn.build/assets/4249734/ccf1a98e-73d6-4a4d-a90e-806e5d33974d)

Concerned that this was my PnP environment, I cloned this repo and attempted `yarn bundle` on `examples/lorem-ipsum` and got the following, distinct error

![image](https://github.com/ojkelly/yarn.build/assets/4249734/4d5c267b-f649-41e7-9fd8-4745b4b6d936)

**To Reproduce**
1. Clone this repo
2. Run `yarn build`
3. Scope to `examples/lorem-ipsum`
4. Run `yarn bundle`

**Expected behavior**
An outputted bundle

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Pro x64
 - Node: 20.9.0

**Comment by Animalmix55** [comment]
It is also worth noting: running `yarn plugin import https://yarn.build/latest` downloads a distinct copy of the bundler (`@ojkelly/plugin-all`) from what is installed in this repo, which seems peculiar. It almost appears as if it is still downloading a version meant for yarn 3. When I copy the plugins from this repo into mine, the following error occurs upon running `yarn bundle`:
 
![image](https://github.com/ojkelly/yarn.build/assets/4249734/41f29172-51fd-434f-a1fa-1649a0f69120)
(which is the same as the one above from `lorem-ipsum`)

**Comment by cmark1302** [comment]
It looks it's already supported as part of this [MR](https://github.com/ojkelly/yarn.build/pull/267).

@ojkelly would you mind update the url with latest yarn 4?

**Comment by ojkelly** [comment]
This is now fixed. @cmark1302 it took a little while to get the release workflow working again as GitHub deprecated the action, among other changes in the bundler output.

All sorted now with a much better release plugin.
