### ISSUE TITLE
Does not work with yarn 4.1

### ISSUE THREAD

**Issue by alamothe** [ojkelly/yarn.build#271]
Installed it on yarn 4.1 but getting error as soon as I start yarn:
```
~/projects/xyz $ yarn
Usage Error: This plugin cannot access the package referenced via node:process which is neither a builtin, 
nor an exposed entry (when initializing @ojkelly/plugin-build, defined in /Users/alamothe/projects/xyz/.yarnrc.yml)
```

making yarn unusable

**Comment by ojkelly** [comment]
I wrote a post-processing script for what comes out of the bundler which fixes this up, can you try the latest release and let me know if it's still happening.

**Comment by alamothe** [comment]
Thank you so much for fixing their crappy bundler.
