### ISSUE TITLE
Tree Shaking

### ISSUE THREAD

**Issue by patrickml** [ojkelly/yarn.build#272]
I have been unable to find any information on tree shaking when it comes to using yarn build.  I noticed that when I switched to using the ESM modules our memory footprint is much higher. I am curious what others are doing for tree shaking with yarn.build and Typescript + ESM.

**Comment by ojkelly** [comment]
yarn.build operates at the `package.json#scripts` level, in that we're effectively orchestrating which package's scripts to call, and what order we need to do that in.

There's nothing specific to yarn.build regarding typescript+esm, that's all left up to the bundler you're using.
