### ISSUE TITLE
[BUG] Targetted builds destroy valid cache entries

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#38]
**Describe the bug**
Targetted builds cause previously valid builds to be evicted from teh build cache.

**To Reproduce**
1. Run `yarn build`
2. Run `yarn build` in `packages/examples/lorem-ipsum`
3. Inspect `local-build-cache.json`

**Expected behavior**
All previously built projects remain in the build cache, so they aren't needlessly rebuilt.

**Desktop (please complete the following information):**
 - OS: Windows/WSL

**Comment by ojkelly** [comment]
The latest release changed the structure of the build cache quite a bit (mostly, just emitting a lot of what was not written out before), and as such I moved it to `.yarn/yarn.build.json`. Partly to make this file more obvious what it is, and where it's coming from. But also to prevent breaking.

I can't seem to replicate this on macOS. Are you able to post the before/after build cache file? And can you try with the latest version.

**Comment by oliversalzburg** [comment]
Aha. I didn't notice the file change and was actually quite confused why my projects refuse to be rebuild (even though I delete the file). I thought this was a new bug.

I will look into this again tonight and you'll have my report in the morning 😄

**Comment by oliversalzburg** [comment]
I haven't noticed any more critical issues like this. I will observe further and report again if needed.
