### ISSUE TITLE
[FEAT] Rebuild command that ignores build state

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#42]
**Is your feature request related to a problem? Please describe.**
Sometimes my projects need to be rebuilt even though yarn.build doesn't recognize it. Sometimes external factors changed that have an outcome on the build, that are not easily deduced.

**Describe the solution you'd like**
A command like `yarn rebuild` that ignores the build cache and just builds the target.

**Describe alternatives you've considered**
Deleting the build cache before running `yarn build`, but that deletes the cache for all modules, not just the target. And it's not as nice as a purpose-built command.

**Comment by oliversalzburg** [comment]
Bummer: https://yarnpkg.com/cli/rebuild 😄

**Comment by ojkelly** [comment]
Ooh, try `yarn build --ignore-cache`, I added that recently. Can also be done on a targeted build so `yarn build packages/example --ignore-cache`

I'm gonna find some time soon to write out some detailed documentation.

**Comment by oliversalzburg** [comment]
That works very well. I don't think I need anything else for this 😄
