### ISSUE TITLE
[FEAT] Write a VS Code Problem Matcher for yarn.build output

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#49]
**Is your feature request related to a problem? Please describe.**
When using `yarn.build` as the default build tool, the `$tsc` problem watcher doesn't work correctly, as the filename is not correctly matched.

**Describe the solution you'd like**
A new problem matcher (maybe in an extension) that handles this output.

**Describe alternatives you've considered**
Maybe the output of yarn.build can be adjusted to use the existing matchers?

**Additional context**
https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

I've been trying to handle this myself the past few days, but didn't get around to it. There are likely a myriad of matchers needed, depending on tool used.

**Comment by ojkelly** [comment]
This is for when you use vscode to do the build for you yeah?

There's existing code for running yarn.build in CI, which disables the streaming output.

I imagine we would likely want to leverage something like that.

Essentially, detect if we're in CI or have a full tty (ie a user called this from a terminal). Or detect if we're running inside a script.

The CI output should solve this. It'll need to be updated if it doesnt. Essentially, something like run the builds, then output the results sequentially.

**Comment by oliversalzburg** [comment]
Yes, this is when VS Code runs the build task. By setting a `problemMatcher` in the task, VS Code can pick up, for example TypeScript compilation errors, and present them in the problems panel.

The CI output might work. I have thought of that, but didn't know how to force that output mode. Ultimately, I'd like to keep the dynamic output though, if possible.

There are a lot of adjusted problem matchers for these cases available. https://github.com/eamodio/vscode-tsl-problem-matcher has quite a few. So I figured I should be able to write something similar for yarn.build.

**Comment by ojkelly** [comment]
When there are build errors, the whole output from the command is printed at the end (at least its meant to be). I would have thought that the problem matches would find that. They might get tripped up by the stuff added before though?

at the moment forcing a ci build is probably easiest by setting `IS_CI=true`.

**Comment by ojkelly** [comment]
I'm going to close this issue, but feel free to re-open or comment if you are still having trouble or have more information.

Additionally, the output was recently cleaned up and all the decoration was removed, which should help with this use case.
