### ISSUE TITLE
Improve stdout in CI

### ISSUE THREAD

**Issue by ojkelly** [ojkelly/yarn.build#5]
Need to check and ensure the output in CI is helpful, and not missing anything.

**Comment by oliversalzburg** [comment]
I also noticed that the CI environment is not always detected correctly. When we're building our Docker images, we still get the full dynamic output as if we weren't running in CI.

**Comment by ojkelly** [comment]
I just checked, it looks like while `is-ci` is being imported, it's no longer being used which isn't intentional.

**Comment by oliversalzburg** [comment]
What's confusing is, I get the short output in one CI phase (where I just invoke `yarn build` on the runner image) and when I build my containers with kaniko, then I get the long output.

On my workstation, setting `CI=true` also seemed to have the desired effect. I assumed this was specific to my build environment.

**Comment by ojkelly** [comment]
Yeah I think it’s partly just a small bug of not checking for ci properly. I also want to fallback to cut mode when no tty is available

**Comment by NoxHarmonium** [comment]
Is there a way to log the stdout even for successful builds? We like to log everything so we can keep an eye on any build warnings etc.

**Comment by ojkelly** [comment]
yeah full output in CI is ideal.

**Comment by ojkelly** [comment]
The output was recently cleaned up, and a duplication issue was found and resolved.

A bunch of decoration on the output was also removed as it wasn't helping.

**Comment by Inlustra** [comment]
I realize I'm a little late on this but I'd love to understand the expected behavior for logs in CI.
Is yarn.build supposed to still output logs like the following? 

```
#26 17.01 [2] packages/connectors@plugsy/connectors (tsc --build) 5.18s
#26 17.01 [ 0:0/5 5.70s ]-----------------------------------------------------------------
#26 17.10 [ build for All ]---------------------------------------------------------------
#26 17.10 [1] packages/common@plugsy/common (tsc --build) 5.27s
#26 17.10 [2] packages/connectors@plugsy/connectors (tsc --build) 5.27s
#26 17.10 [ 0:0/5 5.79s ]-----------------------------------------------------------------
#26 17.19 [ build for All ]---------------------------------------------------------------
#26 17.19 [1] packages/common@plugsy/common (tsc --build) 5.37s
#26 17.19 [2] packages/connectors@plugsy/connectors (tsc --build) 5.36s
#26 17.19 [ 0:0/5 5.88s ]-----------------------------------------------------------------
#26 17.28 [ build for All ]---------------------------------------------------------------
#26 17.29 [1] packages/common@plugsy/common (tsc --build) 5.46s
#26 17.29 [2] packages/connectors@plugsy/connectors (tsc --build) 5.46s
#26 17.29 [ 0:0/5 5.97s ]-----------------------------------------------------------------
#26 17.38 [ build for All ]---------------------------------------------------------------
#26 17.38 [1] packages/common@plugsy/common (tsc --build) 5.55s
#26 17.38 [2] packages/connectors@plugsy/connectors (tsc --build) 5.55s
#26 17.38 [ 0:0/5 6.07s ]-----------------------------------------------------------------
#26 17.47 [ build for All ]---------------------------------------------------------------
#26 17.47 [1] packages/common@plugsy/common (tsc --build) 5.64s
#26 17.47 [2] packages/connectors@plugsy/connectors (tsc --build) 5.64s
#26 17.47 [ 0:0/5 6.16s ]-----------------------------------------------------------------
```

In CI this results in a absolutely massive and semi-useless log, especially if it's long running. 
This is in Github Actions.

Would love to know if there's a solution to this, could perhaps be added to the readme if it does!

**Comment by ojkelly** [comment]
nope thats very much undesired.

I've had a bit of a look around, and checked a recent run in Github Actions, and it looked good there.

There is a CI check done using the `is-ci` package here https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/supervisor/index.ts#L551

and a couple of other times in that file.

It's generally really good at picking out if it really is running in ci, see the list of supported https://github.com/watson/ci-info#supported-ci-tools

Additionally the presence of a variable `CI` is a good fallback.

The additional lines at the start of your output suggest something may be wrapping `yarn build`?
this stuff `#26 17.38 [2]`

If you're running in say a docker container, or something that may reduce the set of ENV vars, that would trip up the CI check.

Can you try run it as `CI=true yarn build`.

Or try setting the ENV in the action:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn build
        env:
          CI: true
```

**Comment by jacobwgillespie** [comment]
> The additional lines at the start of your output suggest something may be wrapping `yarn build`?

The `#26` looks suspiciously like Docker / BuildKit - if that's the case, you might try something like the following in your Dockerfile to temporarily set `CI=true` when running the build command (but not persist it to the built container like `ENV CI=true` would do):

```Dockerfile
RUN env CI=true yarn build
```

**Comment by Inlustra** [comment]
That's exactly right @jacobwgillespie thanks guys.

**Comment by ojkelly** [comment]
Awesome, I'll add a note to the readme.
