### ISSUE TITLE
Long build durations are not rendered nicely

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#59]
**Describe the bug**
Builds that take longer than a minute create weird output. See screenshot.

**To Reproduce**
1. Run a build that takes longer than 1 minute.

**Expected behavior**
The minutes need to be rounded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/103281158-6d430280-49d2-11eb-9d29-7ec3e61d0e72.png)

**Desktop (please complete the following information):**
 - OS: Windows/WSL

**Comment by ojkelly** [comment]
Oh good find. It's probably a small fix.

**Comment by ojkelly** [comment]
fixed by #60 thanks to @Samantha-uk, pending a release with another fix
