### ISSUE TITLE
failed to install yarn.build plugin 

### ISSUE THREAD

**Issue by dongyuwei** [ojkelly/yarn.build#74]
**Describe the bug**

**To Reproduce**
1. npm install -g yarn@berry
2. yarn plugin import https://yarn.build/latest
3. See error

**Expected behavior**
Okay to install yarn.build plugin 

**Screenshots**
```bash
yarn plugin import https://yarn.build/latest
➤ YN0001: ReferenceError: name is not defined
    at /usr/local/lib/node_modules/yarn/bin/yarn.js:58:32838
    at async Function.start (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:44856)
    at async u.execute (/usr/local/lib/node_modules/yarn/bin/yarn.js:58:32187)
    at async u.validateAndExecute (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:40434)
    at async c.run (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:533800)
    at async c.runExit (/usr/local/lib/node_modules/yarn/bin/yarn.js:36:533934)
➤ YN0000: Failed with errors in 0.12s

 yarn -v
2.0.0-rc.27
```
![image](https://user-images.githubusercontent.com/112451/107309465-72ad6580-6ac5-11eb-8a8a-41c9ce04819e.png)

**Desktop:**
 - OS: macOS and Windows

**Comment by emilio-martinez** [comment]
@dongyuwei this may be related to you installing yarn berry as a global. As you'll see from the [installation instructions](https://yarnpkg.com/getting-started/install), the yarn you install globally is v1, while v2 is installed locally.

**Comment by ojkelly** [comment]
that's a good point @emilio-martinez with both yarn berry and yarn build they are intended to be bundled into your repository (in the `.yarn` folder).

Yarn build is not something you can install globally.

Can you try installing it again but without installing globally and see if it works?

**Comment by ojkelly** [comment]
I'm going to close this issue, but feel free to re-open or comment if you are still having trouble or have more information.
