### ISSUE TITLE
Specify max concurrency from command line

### ISSUE THREAD

**Issue by NoxHarmonium** [ojkelly/yarn.build#75]
**Is your feature request related to a problem? Please describe.**

I have a large project with heavy weight build processes.

At one point of our build, eight builds are running at once, and our build server falls over due to lack of memory.

**Describe the solution you'd like**

For a basic solution, specifying the maximum concurrency of a build from the command line would suffice.

However, it might be even better to be able to specify it in config as well.

**Describe alternatives you've considered**

Creating a fake dependency graph to force the builds to run in specific groups

**Additional context**

I have been working on a solution and should be able to open a PR to solve this issue shortly.

**Comment by ojkelly** [comment]
🎉 merged thanks!
