### ISSUE TITLE
Is it possible to bundle a single workspace of a monorepo?

### ISSUE THREAD

**Issue by carlgieringer** [ojkelly/yarn.build#82]
Hi, does it work to bundle just one workspace of a monorepo?  I have a monorepo with multiple applications. An API server, a client, a browser extension. I would like to cd into the `api/` workspace subdirectory and run `yarn bundle` to bundle only that source and its dependencies. Is that supported?

When I try that now, I got a strange error relating to one of the other sub-folders. `infra` is a top-level directory in my monrepo, but it contains only terraform code. So I'm not sure what the error is. I would have expected yarn.build to ignore this directory.

```
Internal Error: ENOENT: no such file or directory, chmod '/private/var/folders/by/tbsr_6z13g37l2zld8xrg4hw0000gn/T/xfs-c8cbed0c/infra/.terraform/modules/295b6bd40c1b71e9361d2aebc0842ff5'
Error: ENOENT: no such file or directory, chmod '/private/var/folders/by/tbsr_6z13g37l2zld8xrg4hw0000gn/T/xfs-c8cbed0c/infra/.terraform/modules/295b6bd40c1b71e9361d2aebc0842ff5'
```

**Comment by ojkelly** [comment]
I'm going to close this issue, but feel free to re-open or comment if you are still having trouble or have more information.
