### ISSUE TITLE
Distributed builds

### ISSUE THREAD

**Issue by danrha** [ojkelly/yarn.build#83]
I have two different web apps and their dependencies in a yarn monorepo. Many of the dependencies are used by both apps so I wanted a way to reuse the build output of dependencies for app builds in different CI jobs.

I'm willing to work on it too if you think it's a good idea :) 

### Current setup
* Job 1: run `yarn workspace app-1 build`, which builds deps first and then bundles app-1
* Job 2: run `yarn workspace app-2 build`, which builds deps first and then bundles app-2

### Ideal setup
* Job 1: run `yarn workspace dep-x build`, which builds dep-x and its dependencies
* Job 2: run `yarn workspace dep-y build`, which builds dep-y and its dependencies
* Job 3 (after 1 & 2 finish): run `yarn workspace app-1 build` which would not have to build `dep-x` or `dep-y`.
* Job 4 (after 1 & 2 finish): run `yarn workspace app-2  build` which would not have to build `dep-x` or `dep-y` either.

I could build all dependencies in one job and then run separate app build jobs in parallel if I pass build artifacts and yarn.build.json, but I have no way of merging the build cache automatically as in the explained ideal setup.

### Easy solution

Splitting the build cache into separate per-package status files (instead of using just one) would allow me to pass success status to following pipeline steps.

Instead of having `.yarn/yarn.build.json`, we'd have something like `.yarn/yarn.build/dep-x.json`, `dep-y.json`, `app-1.json`, etc., describing the status of each package individually.

### Alternate solution

Being able to configure custom checks for the plugin in `.yarnrc.yml`, so I could skip the build from subsequent jobs if output artifacts exist or any other condition I could use to detect if the build exists based on directory state.

This approach could also allow for "force rebuild" conditions as well (if we depend on something external).

### Hacky solution

Write to `.yarn/yarn.build.json` directly on the pipeline jobs to update its state based on checking which files are there before running `build`. This isn't really a suggestion for yarn.build but a hacky workaround to get what I need working. I don't really think it's ok to manipulate your plugin's internal state from outside or if it's schema could change in future versions.

**Comment by ojkelly** [comment]
Ooh interesting. It almost sounds like you want a way to tell `yarn build` that something is already built?

Breaking `.yarn/yarn.build.json` into multiple files is probably overbuilding, as it's structure is used internally as part of the build tracking. So we'd have to scan the directories, and write out multiple files.

The `build` command itself does checks on if a run is needed, such as here https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/supervisor/index.ts#L441

And the `plan` function manages finding and determining what needs to be built and in what order https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/supervisor/index.ts#L365


---

> I could build all dependencies in one job and then run separate app build jobs in parallel if I pass build artifacts and yarn.build.json

Note: if you have sufficient concurrency in your CI build this is precisely what yarn.build does. So, you might not need to do anything if you have 2 CPU's available in your CI.

**Comment by danrha** [comment]
Hey @ojkelly! Thank you so much for the quick response!

Do you think it makes sense to add an option so that we could use `folderConfiguration` info and build or skip by comparing the modified date of the source vs. output folders instead of the manifest (or if the manifest doesn't exist)?

**Comment by ojkelly** [comment]
I think `--skipIfOutputExists` for `build` is a good addition to solve for this.

I am still a bit curious why you can't build everything once, and then split off and do other tasks with the results. Mainly because it breaks the soundness of the whole solution.

For example if you run `yarn build` in the top directory, it will determine the optimal plan to build everything, and parallelise it as much as possible.

**Comment by ojkelly** [comment]
I'm going to close this issue, but feel free to re-open or comment if you are still having trouble or have more information.
