### ISSUE TITLE
Missing @yarnpkg/libzip

### ISSUE THREAD

**Issue by natew** [ojkelly/yarn.build#85]
After adding plugin, any yarn command produces this:

```
$ yarn bundle
Usage Error: This plugin cannot access the package referenced via @yarnpkg/libzip which is neither a builtin, nor an exposed entry (when initializing @ojkelly/plugin-build, defined in /Users/n8/dish/.yarnrc.yml)

Yarn Package Manager - 2.0.0-rc.27
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur

**Additional context**

Yarn global is 2.0.0-rc.27 but I've run `yarn set version latest` and that shows 2.4.2.

I tried adding it as a package.json but it doesn't seem to pick it up.

**Comment by ojkelly** [comment]
hey @natew if you look in `.yarnrc.yml` the `yarnPath` should have the version being used in the repo.

Are you able to provide a small example repo?

This isn't something I've been able to reproduce with yarn 2.4.2.

`yarn bundle` does need to be either run from inside the package you want to bundle.

**Comment by ojkelly** [comment]
I haven't been able to reproduce this, feel free to reopen if you have repro steps.
