### ISSUE TITLE
Plugin missing - 404

### ISSUE THREAD

**Issue by Globolobo** [ojkelly/yarn.build#94]
**Describe the bug**
When running `yarn plugin import https://yarn.build/v2` get a: `YN0001: HTTPError: Response code 404 (Not Found)` 

**To Reproduce**
1. Run command `yarn plugin import https://yarn.build/v2`
3. See error

**Expected behavior**
I'd be able to download the plugin

**Screenshots**
![Screen Shot 2021-07-29 at 11 40 23 am](https://user-images.githubusercontent.com/7945116/127418332-c58f396d-7bd4-4876-829d-35dde0ec1696.png)

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by ojkelly** [comment]
Great catch!

Sorry the reference to it was update to be `.cjs` instead of `.js`. Not applicable to the yarn 2 version of the plugin only the yarn 3 version.

Fixed here c072e12

**Comment by Globolobo** [comment]
Thanks for the quick fix! Will be checking this out later
